[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "postgresql", "nodejs"]

[phases.install]
cmds = [
    "cd backend/install && composer install --optimize-autoloader --no-dev --no-interaction"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend/install && php artisan serve --host=0.0.0.0 --port=$PORT"
